package io.pivotal.trilogy.testrunner

class UnexpectedArgumentException(message: String, cause: Throwable): RuntimeException(message, cause)